// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUoE_XX79smLsQamUGL6736odkt0gnqFY',
    appId: '1:1018382543358:web:94b6f08be17215eff738af',
    messagingSenderId: '1018382543358',
    projectId: 'fir-auth-b3c12',
    authDomain: 'fir-auth-b3c12.firebaseapp.com',
    storageBucket: 'fir-auth-b3c12.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhbl8j5ijfLK0cn6-H4ktJU8J2VvKYhXc',
    appId: '1:1018382543358:android:7737b3419d72e880f738af',
    messagingSenderId: '1018382543358',
    projectId: 'fir-auth-b3c12',
    storageBucket: 'fir-auth-b3c12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQXZfcedyRqBOfU8tSSJScmeQhMrkHD7A',
    appId: '1:1018382543358:ios:2e1564381fcb3d5df738af',
    messagingSenderId: '1018382543358',
    projectId: 'fir-auth-b3c12',
    storageBucket: 'fir-auth-b3c12.firebasestorage.app',
    iosBundleId: 'com.example.fileAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQXZfcedyRqBOfU8tSSJScmeQhMrkHD7A',
    appId: '1:1018382543358:ios:2e1564381fcb3d5df738af',
    messagingSenderId: '1018382543358',
    projectId: 'fir-auth-b3c12',
    storageBucket: 'fir-auth-b3c12.firebasestorage.app',
    iosBundleId: 'com.example.fileAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUoE_XX79smLsQamUGL6736odkt0gnqFY',
    appId: '1:1018382543358:web:eed1d4b6dae8d8a6f738af',
    messagingSenderId: '1018382543358',
    projectId: 'fir-auth-b3c12',
    authDomain: 'fir-auth-b3c12.firebaseapp.com',
    storageBucket: 'fir-auth-b3c12.firebasestorage.app',
  );
}
